### PR TITLE
Post session message for native app

### PR DESCRIPTION
**Pull request by diegomura**
Notifies the native app for updates in the session state

### CODE REVIEW

**Comment by diegomura** [comment]
Thanks @tpreusse !
I was expecting fixes like these. I added the base post messaging communication, but I was aware of some of the issues you mention. 

*re serialization:* The message should be any type of data, but for some reason on Android devices I was not getting objects correctly 

*everything else*: agreed! Working on it

**Comment by tpreusse** [comment]
Is there any urgent need to have this in prod? Otherwise should we create a app branch and merge all PR to there until things like UA ready to go master/prd?

**Comment by diegomura** [comment]
No urgent at all,  but until we do both Android and iOS I'll release for you to test it won't work, since those are pointing to prod. 

Is there any staging environment we can use to test the apps? That would be ideal. I can easily make the apps point to there, and we can release these changes to also test them before prod

**Comment by tpreusse** [comment]
Let's do a `app` branch with auto-deploy to a staging frontend pointing a prod. You could send a basic auth header in the web view right?

**Pull request merged**
