### PR TITLE
Add SVG favicon and white background to fallback icons

### PR DESCRIPTION
**Pull request by ovbm**
Chrome (left localhost, right live)
Screenshot 2021-05-04 at 16 34 44
Screenshot 2021-05-04 at 16 34 55

Firefox (left localhost, right live)
Screenshot 2021-05-04 at 16 36 10
Screenshot 2021-05-04 at 16 35 36

Safari: no change

### CODE REVIEW

**Comment by ovbm** [comment]
Screenshot 2021-05-04 at 16 49 21
Screenshot 2021-05-04 at 16 49 16
Screenshot 2021-05-04 at 16 48 51
Screenshot 2021-05-04 at 16 48 45

**Comment by ovbm** [comment]
legacy browsers still have the normal favicon-32x32.png, favicon-16x16.png and favicon.ico as fallbacks. they all have white backgrounds now

**Review by tpreusse — APPROVED** [review]
Awesome. Thx.

**Comment by ovbm** [comment]
Tagesanzeiger is using svg icons as far as I can tell. at least they switch on dark mode on firefox and chrome just like in this pr

**Pull request merged**
